version: "3"

services:
  db:
    container_name: splusdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: splus
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: